### ISSUE TITLE
Forcing shared instance

### ISSUE THREAD

**Issue by mindplay-dk** [sjinks/php-memory-cache#1]
You've privatized the constructor, forcing consumers to share a single instance of the cache.

Using a shared cache leads to side-effects and key collisions - and I understand you created this cache explicitly for the purpose of testing, but these problems are actually even more likely to occur under test.

That's generally not how PSR-16 caches should be used - we don't have the concept of cache pools (as in PSR-6) and therefore you should think of every instance of `CacheInterface` as a cache-pool.

That means you rarely create a single cache and share it between consumers, except when those consumers were explicitly designed to share the same cache instance, which is rare. (and in those cases, you still wouldn't use a singleton, you'd use dependency injection and bootstrapping to explicitly inject the same instance to those specific consumers.)

**Comment by sjinks** [comment]
Fixed, thank you!

**Comment by mindplay-dk** [comment]
Looks good, just needs a tag :-)

**Comment by sjinks** [comment]
1.0.4 should be there
